### ISSUE TITLE
No Sound For Banana Gun

### ISSUE THREAD

**Issue by LoadingPleaseWait** [VersatileVelociraptors/Velocicopterpp#1]
Shooting the banana gun produces no sound.

**Comment by amadvani** [comment]
If you listen closely, there is sound playing but since the banana gun has such a high rate of fire, the sound restarts almost instantly for the next shot. This seems to be a limitation of SFML.

**Comment by LoadingPleaseWait** [comment]
Perhaps we could make the sound shorter so that it sounds more like it does in our Java repository?
